[package]
org = "tharana_wanigaratne"
name = "sonar_bal_testing"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

# For custom rules analysis with Ballerina Scan Tool (No longer needed as these can be mentioned in a Scan.toml file)
#[[dependency]]
#version="0.1.0"
#org = "tharana_wanigaratne"
#name = "compiler_plugin_customRules"
#repository="local"

# For plain text password saving rule testing
# [[platform.java17.dependency]]
# artifactId = "h2"
# version = "2.0.206"
# groupId = "com.h2database"