[package]
org = "tharana_wanigaratne"
name = "sonar_bal_testing"
version = "0.1.0"
distribution = "2201.9.0"

# For plain text password saving rule testing
# [[platform.java17.dependency]]
# artifactId = "h2"
# version = "2.0.206"
# groupId = "com.h2database"