# =========================================================
# all following are optional (populated with defaul values)
# =========================================================
# For platform specific properties to get picked up, the path should be valid
[[platform]]
name = "sonarqube"
path = "C:\\Users\\Tharana Wanigaratne\\Desktop\\ballerina-scan-tool\\sonar-platform-plugin\\build\\libs\\sonar-platform-plugin-1.0.jar"


[[plugin]]
org = "tharana_wanigaratne"
name = "custom_static_code_analyzer"
version = "0.1.0"


#[[rule]]
#id = "S107"
#
#[[rule]]
#id = "S108"
#
#[[rule]]
#id = "S109"