[[platform]]
name = "sonarqube"
path = "C:\\Users\\Tharana Wanigaratne\\Desktop\\ballerina-scan-tool\\sonarqube-platform-plugin\\build\\libs\\sonarqube-platform-plugin-1.0.jar"
#sonarProjectPropertiesPath = "sonar-project.properties"

[[plugin]]
org = "tharana_wanigaratne"
name = "custom_static_code_analyzer"
version = "0.1.0"

[rule]
ids = "S107, S108"